status = error
name = SparkLog4j2Config

# Корневой логгер: WARN — безопасный баланс
rootLogger.level = warn
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = Console

# Логи твоего приложения
logger.app.name = ru.otus.homework
logger.app.level = info

# Spark и Hadoop: без мусора, но WARN остаётся
logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn

# Инфраструктурный шум — в ERROR
logger.jetty.name = org.eclipse.jetty
logger.jetty.level = error

logger.netty.name = io.netty
logger.netty.level = error

# Console appender
appender.Console.type = Console
appender.Console.name = Console
appender.Console.target = SYSTEM_ERR
appender.Console.layout.type = PatternLayout
appender.Console.layout.pattern = %d{HH:mm:ss} %-5p %c{1} - %m%n
