status = error
name = SparkLog4j2Config

# По умолчанию всё ERROR (почти нет мусора)
rootLogger.level = error
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = Console

# Настройки Spark/Hadoop
logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = error

logger.netty.name = io.netty
logger.netty.level = error

appender.Console.type = Console
appender.Console.name = Console
appender.Console.target = SYSTEM_ERR
appender.Console.layout.type = PatternLayout
appender.Console.layout.pattern = %d{HH:mm:ss} %-5p %c{1} - %m%n
